workflows:
  android-release:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      java: 17
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Flutter clean
        script: flutter clean
      - name: Flutter pub get (after clean)
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
